apiVersion: v1
kind: Service
metadata:
  name: travelly
  labels:
    app: travelly
spec:
  type: ClusterIP
  selector:
    app: travelly
  ports:
  - protocol: TCP
    port: 8080
    targetPort: tomcat-default