apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelly-frontend
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels: 
      app: travelly-frontend
  template:
    metadata:
      labels:
        app: travelly-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: frontend
        image: ghcr.io/dev-ops-fmi/travelly-frontend:v1.0.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 2
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 2
      imagePullSecrets:
      - name: ghcr-pull
        

