apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
secretGenerator:
  - name: db-credentials
    type: kubernetes.io/basic-auth
    behavior: create
    files:
      - username
      - password
generatorOptions:
  disableNameSuffixHash: true