name: Deploy to Kubernetes Cluster

on:
  workflow_dispatch:
    inputs:
      overlay:
        type: choice
        description: Which overlay to deploy
        required: true
        options:
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.28.2'

      - name: Prepare Kubeconfig
        run:  echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      
      - name: Deploy Common
        run: kubectl apply -k common/

      - name: Generate Github Container Registry Pull Secret
        run: 
          kubectl create secret docker-registry ghcr-pull \
            -n travelly-internal \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.DOCKER_USER }} \
            --docker-password=${{ secrets.DOCKER_PASS }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }}

      - name: Install NGINX Ingress Controller
        run:
          k apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.5/deploy/static/provider/cloud/deploy.yaml

      - name: Deploy Manifests
        run:
          k apply -k /overlays/${{ github.event.inputs.overlay }}
        

      